### ISSUE TITLE
Can't set breakpoint on VRAM

### ISSUE THREAD

**Issue by romhack** [lab313ru/Gensida#10]
During debugger loading, there's a warning: "No i/o port definitions for device 'GensIDA' are found"
And when I pause the game to add a breakpoint it only can be placed on ROM address. No additional window appeares after pressing OK at initial breakpoint definition screen.
Tried on latest release and 1.2. Windows 7 64bit.

**Comment by lab313ru** [comment]
First warning is normal. Just OK it.

Try to view this video: https://m.youtube.com/watch?v=ADUbNv-6G0M
And some other related. It explains where to set breakpoints, and how to use Gensida.

**Comment by lab313ru** [comment]
Also, check this page: http://www.emu-land.net/forum/index.php?topic=74337.0 and my site http://lab313.ru to find all related videos and info.

**Comment by lab313ru** [comment]
This pave contains all videos: http://forum.lab313.ru/index.php?forums/sega-genesis-mega-drive-articles.20/

**Comment by romhack** [comment]
Thanks for your concearn! Now it's clear.
If I may, I can recommend to add small info regarding DBG segments or links to videos in readme.md.

**Comment by lab313ru** [comment]
Yep, I'll add it today. Thank you)
